 version: '3'
 services:

   mqfull:
     build: mq
     environment:
       LICENSE: accept
       MQ_QMGR_NAME: QM1
     # MQSNOAUT - This environment variable disables all authorization checking in MQ. 
     # This is not recommended for production environments
       MQSNOAUT: "yes"
     ports:
       - "1414:1414"
       - "9443:9443"
   sender:
     build: liberty-sender
     ports:
       - "10080:9080"
       - "10443:9443"
   receiver:
     build: liberty-receiver
     ports:
       - "10081:9080"
       - "10444:9443"
